### ISSUE TITLE
Return files properly in the runTask

### ISSUE THREAD

**Issue by yilinwei** [to-ithaca/sbt-directive#10]

**Comment by zainab-ali** [comment]
The `directive` task generates sources, but instead of adding the `Seq[File]` to the generated sources, we switch the `scalaSource` directory to the generated sources directory.
We could try removing the `scalaSource` directory some other way - the sources themselves won't compile.

**Comment by zainab-ali** [comment]
Completed as part of #20 .
`scalaSource` now points to a non-existent directory. Both `scala` and `java` generated sources are added to the generated source list.
